<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>MineYourBusiness</RootNamespace>
    <AssemblyName>MineYourBusiness</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/MineYourBusiness.Game/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src/MineYourBusiness.Domain/MineYourBusiness.Domain.csproj" />
  </ItemGroup>
</Project>
